"""create stage 1 questionnaire tables

Revision ID: b071e92464b2
Revises:
Create Date: 2026-07-10 00:03:46.721187
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b071e92464b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_bank',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('question_version', sa.String(length=32), nullable=False),
    sa.Column('questionnaire_version', sa.String(length=64), nullable=False),
    sa.Column('primary_dimension', sa.String(length=64), nullable=True),
    sa.Column('secondary_dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scale_min', sa.Integer(), nullable=True),
    sa.Column('scale_max', sa.Integer(), nullable=True),
    sa.Column('is_seed', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_bank_primary_dimension'), 'question_bank', ['primary_dimension'], unique=False)
    op.create_index(op.f('ix_question_bank_questionnaire_version'), 'question_bank', ['questionnaire_version'], unique=False)
    op.create_table('questionnaire_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('anonymous_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('questionnaire_version', sa.String(length=64), nullable=False),
    sa.Column('profile_schema_version', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('completion_reason', sa.String(length=32), nullable=True),
    sa.Column('final_profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_summary', sa.Text(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('session_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_occurred', sa.Boolean(), nullable=False),
    sa.Column('abandoned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'processing', 'needs_retry', 'complete', 'abandoned')", name='ck_questionnaire_sessions_status'),
    sa.CheckConstraint('total_questions BETWEEN 0 AND 12', name='ck_session_question_count'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_sessions_anonymous_user_id'), 'questionnaire_sessions', ['anonymous_user_id'], unique=False)
    op.create_index(op.f('ix_questionnaire_sessions_status'), 'questionnaire_sessions', ['status'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('event_properties_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['questionnaire_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_event_name'), 'analytics_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_analytics_events_session_id'), 'analytics_events', ['session_id'], unique=False)
    op.create_table('session_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=128), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('exact_question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('primary_dimension', sa.String(length=64), nullable=True),
    sa.Column('secondary_dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('options_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scale_min', sa.Integer(), nullable=True),
    sa.Column('scale_max', sa.Integer(), nullable=True),
    sa.Column('selection_reason', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('displayed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_time_seconds', sa.Float(), nullable=True),
    sa.Column('confidence_before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['questionnaire_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_order', name='uq_session_question_order')
    )
    op.create_index(op.f('ix_session_questions_question_id'), 'session_questions', ['question_id'], unique=False)
    op.create_index(op.f('ix_session_questions_session_id'), 'session_questions', ['session_id'], unique=False)
    op.create_table('questionnaire_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('session_question_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_response', sa.Text(), nullable=False),
    sa.Column('sanitized_model_input', sa.Text(), nullable=False),
    sa.Column('extracted_information_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("validation_status IN ('pending', 'valid', 'invalid', 'needs_retry')", name='ck_response_validation_status'),
    sa.ForeignKeyConstraint(['session_id'], ['questionnaire_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_question_id'], ['session_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'idempotency_key', name='uq_response_idempotency'),
    sa.UniqueConstraint('session_question_id', name='uq_response_session_question')
    )
    op.create_index(op.f('ix_questionnaire_responses_session_id'), 'questionnaire_responses', ['session_id'], unique=False)
    op.create_table('ai_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('triggering_response_id', sa.UUID(), nullable=True),
    sa.Column('operation_type', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_category', sa.String(length=64), nullable=True),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attempt >= 1', name='ck_ai_runs_attempt'),
    sa.ForeignKeyConstraint(['session_id'], ['questionnaire_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggering_response_id'], ['questionnaire_responses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_runs_session_id'), 'ai_runs', ['session_id'], unique=False)
    op.create_table('profile_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('triggering_response_id', sa.UUID(), nullable=False),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('coverage_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_information_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['questionnaire_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggering_response_id'], ['questionnaire_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'version', name='uq_profile_snapshot_version')
    )
    op.create_index(op.f('ix_profile_snapshots_session_id'), 'profile_snapshots', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_snapshots_session_id'), table_name='profile_snapshots')
    op.drop_table('profile_snapshots')
    op.drop_index(op.f('ix_ai_runs_session_id'), table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_index(op.f('ix_questionnaire_responses_session_id'), table_name='questionnaire_responses')
    op.drop_table('questionnaire_responses')
    op.drop_index(op.f('ix_session_questions_session_id'), table_name='session_questions')
    op.drop_index(op.f('ix_session_questions_question_id'), table_name='session_questions')
    op.drop_table('session_questions')
    op.drop_index(op.f('ix_analytics_events_session_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_name'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_questionnaire_sessions_status'), table_name='questionnaire_sessions')
    op.drop_index(op.f('ix_questionnaire_sessions_anonymous_user_id'), table_name='questionnaire_sessions')
    op.drop_table('questionnaire_sessions')
    op.drop_index(op.f('ix_question_bank_questionnaire_version'), table_name='question_bank')
    op.drop_index(op.f('ix_question_bank_primary_dimension'), table_name='question_bank')
    op.drop_table('question_bank')
    # ### end Alembic commands ###
